# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#Your build pipeline references a secret variable named ‘MachinePassword’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972
variables:
  NumberOfJobs: 3
  # SubscriptionId: "Your Subscription ID is here."

# ----------------------------------
# Make disabled event triggers
# ----------------------------------
pr: none
trigger: none

# ----------------------------------
# Schedule
# ----------------------------------
# schedules:
# - cron: "0 0 * * *"
#   displayName: Daily midnight build
#   branches:
#     include:
#     - master

steps:
  - task: AzurePowerShell@4
    timeoutInMinutes: 360
    inputs:
      azureSubscription: '$SubscriptionId' 
      ScriptType: 'FilePath'
      ScriptPath: 'Exec-Parallel-Jobs.ps1'
      ScriptArguments: '-NumberOfJobs $(NumberOfJobs)'
      azurePowerShellVersion: 'LatestVersion'
